# Generated by Django 6.0.5 on 2026-05-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='apellido',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='salario',
            field=models.CharField(),
        ),
    ]
