# Generated by Django 6.0.5 on 2026-05-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_apellido_alter_clientes_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_clientes'),
        ),
    ]
